### ISSUE TITLE
systray applications

### ISSUE THREAD

**Issue by kupiqu** [ration/krunner-switcher#1]
congrats, very nice idea

I guess not so easy, but wondering whether it could be extended to system tray applications...

**Comment by ration** [comment]
Maybe if there's a place to query the data from somewhere (dbus?). I'm not sure if it's worth the hassle though, I don't think they even take keyboard focus.

**Comment by kupiqu** [comment]
> I don't think they even take keyboard focus.

I see. Thought there was a way
