### ISSUE TITLE
change key

### ISSUE THREAD

**Issue by husimo** [ration/krunner-switcher#2]
I would really like to have the possibility to change the dot keyword.
I use a French (Azerty) keyboard and using the "." is harder than on a Qwerty one (I need to do `Shift+.`)
Thank you, that's a really good piece of software :-)

**Comment by ration** [comment]
There's no configuration for it now, but it's a trivial change in the code. In switcher.cpp line 127 change the dot to whatever you wish.

**Comment by husimo** [comment]
Thank you, that's perfect !
