### ISSUE TITLE
Move mouse to center of newly focused window

### ISSUE THREAD

**Issue by pstephenwille** [ration/krunner-switcher#3]
I was about to give this app a try when I thought of this.  Not sure if others would find it helpful but I sure would.  I use focus-follows-mouse and I hate having to move the cursor to the active window.  Having the cursor put on the active window automatically would sure help keep my hands on the keyboard.  As it stands now, I use Krunner Search to find and bring a window to the foreground, then manually move the mouse to the window.  Ugh, it's such a clumsy work flow.

**Comment by ration** [comment]
Hi, 

I'm not fully convinced that I want this feature enabled by default. Maybe an option if there was a option menu..  

That said, I created a branch named [_move_focus_](https://github.com/ration/krunner-switcher/tree/move_focus) which has this - compile the plugin from there and try it out.

**Comment by pstephenwille** [comment]
Awesome, that sounds great!
I gave the master branch install a try but keep running into this error, even after installing qt5.

```CMake Error at CMakeLists.txt:10 (find_package):
  Could not find a package configuration file provided by "Qt5" (requested
  version 5.9.0) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake
```

**Comment by ration** [comment]
The readme has been updated for all the required packages.
