### ISSUE TITLE
Missing XCB_RANDR_LIBRARY

### ISSUE THREAD

**Issue by tomjuggler** [ration/krunner-switcher#8]
Great plug-in idea - here is what happened when I tried to install though:

```
cmake -DQT_PLUGIN_INSTALL_DIR=`kf5-config --qt-plugins` -DCMAKE_BUILD_TYPE=Release  ..
-- Could NOT find XCB_RANDR (missing: XCB_RANDR_LIBRARY XCB_RANDR_INCLUDE_DIR) (found version "")
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find XCB (missing: RANDR) (found version "1.14")
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindXCB.cmake:166 (find_package_handle_standard_args)
  src/CMakeLists.txt:5 (find_package)
```

-- Configuring incomplete, errors occurred!

Ubuntu Studio 21.04 with KDE Plasma desktop

**Comment by ration** [comment]
Can you try if installing `libxcb-randr0-dev` package resolves this? Curiously I don't see this issue and I don't have it installed (Kubuntu 21.10).

**Comment by thomp** [comment]
I experienced the same CMake error. Installing `libxcb-randr0-dev` resolves the issue for me. 
debian with kde-plasma-desktop (version 5:111)

**Comment by ration** [comment]
Added this to readme
